# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalweb', '0002_auto_20160811_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinder',
            name='resident',
        ),
        migrations.DeleteModel(
            name='Tinder',
        ),
    ]
