version: '2'
services:
  db:
    image: postgres
  cache:
    image: redis
  app:
    build: bone
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    env_file:
      - ./app.env
