version: '2'
services:
  db:
    image: postgres
  cache:
    image: redis
  app:
    build: bone
    ports:
      - "8000:8000"
    volumes:
      - ./bone:/bone
    depends_on:
      - db
      - cache
    env_file:
      - ./app.env
    command: bash -c "./wait-for-it db:5432 -- python3 manage.py runserver 0.0.0.0:8000"
