version: '2'
services:
  db:
    image: postgres
    restart: always
  cache:
    image: redis
    restart: always
  app:
    build: bone
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./bone/media:/bone/media
      - ./bone/static:/bone/static
    depends_on:
      - db
      - cache
    env_file:
      - ./app.env
    restart: always
