# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 02:33
from __future__ import unicode_literals

import boneweb.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kerberos', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to=boneweb.models._picture_upload_to)),
                ('year', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
