# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 13:54
from __future__ import unicode_literals

import boneweb.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0002_auto_20160722_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=boneweb.models._picture_upload_to),
        ),
    ]
