# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0003_auto_20160722_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
