# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0004_resident_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='REXEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
