# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0005_rexevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rexevent',
            options={'verbose_name': 'REX Event', 'verbose_name_plural': 'REX Events'},
        ),
        migrations.AddField(
            model_name='rexevent',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
