# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0006_auto_20160804_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
