# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0007_quote'),
        ('boneweb', '0007_resident_alumni'),
    ]

    operations = [
    ]
