# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('boneweb', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
